name: Build Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 20

      - uses: gradle/actions/setup-gradle@v3

      - run: ./gradlew app:assembleReleaseAndroidTest --scan
